services:
#    jfusion.extension.controller:
#        class: jfusion\extension\controller\main
#        arguments:
#            - @config
#            - @controller.helper
#            - @template
#            - @user

    jfusion.extension.listener:
        class: jfusion\extension\event\main_listener
        arguments:
            - @config
            - @user
        tags:
            - { name: event.listener }

    auth.provider.jfusion:
        class: jfusion\extension\auth\provider\auth
        arguments:
            - @dbal.conn
            - @config
            - @passwords.manager
            - @request
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: auth.provider }